version: '1.0'

services:
  # Serviço do Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-sso-app
    container_name: laravel-sso-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network

  # Serviço do Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel-sso-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

  # Serviço do MySQL
  db:
    image: mysql:5.7
    container_name: laravel-sso-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_sso
      MYSQL_USER: oauth_sso
      MYSQL_PASSWORD: oauth_sso_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
